### ISSUE TITLE
Reference to "Master Template Guide" should be replaced with correct name and link

### ISSUE THREAD

**Issue by jeffdbrown** [OpenPOWERFoundation/Docs-Master#1]
The correct name should be:  OpenPOWER Foundation Documentation Development Guide

The correct link should be:
https://openpowerfoundation.org/?resource_lib=openpower-foundation-documentation-development-guide

**Comment by jjscheel** [comment]
Should be better now.  Please verify and close if you think we're done.

**Comment by jeffdbrown** [comment]
Looks good - thx!
